services:
    db:
        image: mysql:8.4
        container_name: recipe_database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: recipes
            MYSQL_USER: recipes
            MYSQL_PASSWORD: recipes
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "recipes",
                    "-precipes",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db_data:
